#!/bin/bash

set -e

show_usage() {
cat << EOF
  Usage: ${0##*/} [-u esxi_username] [-h esxi_hostname] [-i ssh_key_file] [-a action] [-d datastore] [-b build]
  Do stuff to esxi host and yeah.
EOF
}

OPTIND=1
while getopts "u:h:a:i:d:b:" opt; do
  case $opt in
    u)
      ESXI_USER=${OPTARG}
      ;;
    h)
      ESXI_HOSTNAME=${OPTARG}
      ;;
    a)
      ACTION=${OPTARG}
      ;;
    i)
      ID_FILE=${OPTARG}
      ;;
    d)
      DS=${OPTARG}
      ;;
    b)
      DIR=${OPTARG}
      ;;
    \?)
      echo "Invalid arg: -${OPTARG}"
      show_usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done
shift "$((OPTIND-1))"

SSHCMD="ssh ${ESXI_HOSTNAME} -i ${ID_FILE}"

function power() {
  ${SSHCMD} "vim-cmd vmsvc/${ACTION} \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1)"
}

function register_vm() {
  ${SSHCMD} "vim-cmd solo/${ACTION} /volumes/vmfs/${DS}/${DIR}/packer-centos7.vmx"
}

function clone_vm() {
  ${SSHCMD} "mkdir /vmfs/volumes/${DS}/${OUTDIR}"
  ${SSHCMD} "vmkfstools -i /vmfs/volumes/${DS}/${DIR}/disk.vmdk /vmfs/volumes/${DS}/${OUTDIR}/disk.vmdk"
  ${SSHCMD} "find /vmfs/volumes/${DS}/${DIR} -type f -not -name '*.vmdk' -exec cp {} /vmfs/volumes/${DS}/${OUTDIR}/disk.vmdk \\\;"
  ${SSHCMD} "vim-cmd solo/registervm /volumes/vmfs/${DS}/${OUTDIR}/packer-centos7.vmx"
}

case ${ACTION} in
  power-on|power-off)
    power
    ;;
  registervm)
    ssh ${ESXI_HOSTNAME} -i ${ID_FILE} "vim-cmd solo/${ACTION} /volumes/vmfs/${DS}/${DIR}/packer-centos7.vmx"
    ;;
  *)
    show_usage
    exit 1
    ;;
esac
