#!/bin/bash

set -e

show_usage() {
cat << EOF
  Usage: ${0##*/} [-u esxi_username] [-h esxi_hostname] [-i ssh_key_file] [-a action] [-s size] [-d datastore] [-b build] [-o clone_dir ] [-v]

  -u esxi_username : specify the username to connect to esxi with
  -h esxi_hostname : specify the esxi host
  -i ssh_key_file  : The ssh private key used to log into the esxi server
  -a action        : The action to perform (currently poweron, poweroff, registervm, unregistervm, clonevm, getstate, getip, newdisk)
  -s size          : Size of disk to add if using newdisk action
  -d datastore     : datastore containing the VM we are acting upon
  -b build         : the pipeline build number
  -o clone_dir     : the directory to clone to for clonevm actions
  -v               : be more verbose
EOF
}

OPTIND=1
while getopts "u:h:a:i:s:d:b:o:v" opt; do
  case $opt in
    u)
      ESXI_USER=${OPTARG}
      ;;
    h)
      ESXI_HOSTNAME=${OPTARG}
      ;;
    a)
      ACTION=${OPTARG}
      ;;
    s)
      SIZE=${OPTARG}
      ;;
    i)
      ID_FILE=${OPTARG}
      ;;
    d)
      DS=${OPTARG}
      ;;
    b)
      DIR=${OPTARG}
      ;;
    o)
      OUTDIR=${OPTARG}
      ;;
    v)
      VERBOSE=true
      ;;
    \?)
      echo "Invalid arg: -${OPTARG}"
      show_usage
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      show_usage
      exit 1
      ;;
  esac
done
shift "$((OPTIND-1))"

SSHCMD="ssh ${ESXI_USER}@${ESXI_HOSTNAME} -i ${ID_FILE}"

function power() {
  [[ ${ACTION} = 'poweron' ]] && ACT='power.on' || ACT='power.shutdown'
  if $VERBOSE; then
    echo "${SSHCMD}" "vim-cmd vmsvc/${ACT} \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1)"
  fi
  ${SSHCMD} "vim-cmd vmsvc/${ACT} \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1)"
}

function register_vm() {
  if $VERBOSE; then
    echo "${SSHCMD}" "vim-cmd solo/registervm /vmfs/volumes/${DS}/${DIR}/packer-centos7.vmx ${OUTDIR}"
  fi
  ${SSHCMD} "vim-cmd solo/registervm /vmfs/volumes/${DS}/${DIR}/packer-centos7.vmx ${OUTDIR}"
}

function unregister_vm() {
  if $VERBOSE; then
    echo "${SSHCMD}" "vim-cmd vmsvc/unregister \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1)"
  fi
  ${SSHCMD} "vim-cmd vmsvc/unregister \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1)"
}

function clone_vm() {
  if $VERBOSE; then
    echo "${SSHCMD}" "mkdir /vmfs/volumes/${DS}/${OUTDIR}"
    echo "${SSHCMD}" "vmkfstools -i /vmfs/volumes/${DS}/${DIR}/disk.vmdk -d thin /vmfs/volumes/${DS}/${OUTDIR}/disk.vmdk"
    echo "${SSHCMD}" "find /vmfs/volumes/${DS}/${DIR} -type f -not -name '*.vmdk' -exec cp -v \"{}\" /vmfs/volumes/${DS}/${OUTDIR} \\;"
    echo "${SSHCMD}" "vim-cmd solo/registervm /vmfs/volumes/${DS}/${OUTDIR}/packer-centos7.vmx ${OUTDIR}"
  fi
  ${SSHCMD} "mkdir /vmfs/volumes/${DS}/${OUTDIR}"
  ${SSHCMD} "vmkfstools -i /vmfs/volumes/${DS}/${DIR}/disk.vmdk -d thin /vmfs/volumes/${DS}/${OUTDIR}/disk.vmdk"
  ${SSHCMD} "find /vmfs/volumes/${DS}/${DIR} -type f -not -name '*.vmdk'"
  ${SSHCMD} "find /vmfs/volumes/${DS}/${DIR} -type f -not -name '*.vmdk' -exec cp -v \"{}\" /vmfs/volumes/${DS}/${OUTDIR} \\;"
  ${SSHCMD} "vim-cmd solo/registervm /vmfs/volumes/${DS}/${OUTDIR}/packer-centos7.vmx ${OUTDIR}"
}

function get_ip() {
  if $VERBOSE; then
    echo "${SSHCMD}" "vim-cmd vmsvc/get.summary \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/\" | cut -d\" \" -f1)" | grep ip | awk -F'\"' '{print $2}'
  fi
  ${SSHCMD} "vim-cmd vmsvc/get.summary \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/\" | cut -d\" \" -f1)" | grep ip | awk -F'\"' '{print $2}'
}

function get_state() {
  if $VERBOSE; then
    echo "${SSHCMD}" "vim-cmd vmsvc/get.summary \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/\" | cut -d\" \" -f1)" | grep powerState | awk -F'\"' '{print $2}'
  fi
  ${SSHCMD} "vim-cmd vmsvc/get.summary \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/\" | cut -d\" \" -f1)" | grep powerState | awk -F'\"' '{print $2}'
}

function new_disk() {
  if $VERBOSE; then
    $"{SSHCMD}" "vmkfstools -c ${SIZE}G -d thin /vmfs/volumes/$(DS)/${DIR}/datadisk.vmdk"
    $"{SSHCMD}" "vim-cmd vmsvc/device.diskaddexisting \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1) /vmfs/volumes/$(DS)/${DIR}/datadisk.vmdk 0 1 ${DS}"
  fi
  ${SSHCMD} "vmkfstools -c ${SIZE}G -d thin /vmfs/volumes/$(DS)/${DIR}/datadisk.vmdk"
  sleep 5 # Allow time for ESXi to initialise the disk
  ${SSHCMD} "vim-cmd vmsvc/device.diskaddexisting \$(vim-cmd vmsvc/getallvms | grep \"\[${DS}\] ${DIR}/packer-centos7\" | cut -d\" \" -f1) /vmfs/volumes/$(DS)/${DIR}/datadisk.vmdk 0 1 ${DS}"
}

case ${ACTION} in
  poweron|poweroff)
    power
    ;;
  registervm)
    register_vm
    ;;
  unregistervm)
    unregister_vm
    ;;
  clonevm)
    clone_vm
    ;;
  getstate)
    get_state
    ;;
  getip)
    get_ip
    ;;
  newdisk)
    new_disk
    ;;
  *)
    show_usage
    exit 1
    ;;
esac
